<template>
    <cun-flex wrap x="start" gap="20">
        <cun-avatar
            src="../../../../src/assets/images/程.png"
            status="online"
            status-position="top-left"
        />
        <cun-avatar
            src="../../../../src/assets/images/程.png"
            status="processing"
            status-position="top-left"
        />
        <cun-avatar
            src="../../../../src/assets/images/程.png"
            status="busy"
            status-position="top-right"
        />
        <cun-avatar
            src="../../../../src/assets/images/程.png"
            round
            status="away"
            status-position="bottom-left"
        />
        <cun-avatar
            src="../../../../src/assets/images/程.png"
            round
            status="offline"
            status-position="bottom-right"
        />
    </cun-flex>
</template>
